
version: '3.1'

services:
  fastify_api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:8080
    # env_file:
    #   - ./.env
    volumes:
      - ./:/var/app
    networks:
      - dev-network

networks:
  dev-network:
    driver: bridge